#pragma once
#include <QMainWindow>
#include <QSharedPointer>
#include "UCDialogPathBundles.h"
#include "UCSingleton.h"



class Ui_MainWindow;
class QTreeView;

namespace Uber
{

/*!
* Main UberCode-Window
* Handles main user interaction like opening/saving/configuring created UberCode scenes
* Note: This Window UI is generated by MainWindow.ui
*/
class UCWindowMain : public QMainWindow, public UCSingleton<UCWindowMain>
{
	Q_OBJECT 	/*!< QObject - macro need to be included to create qt-class */

	typedef QSharedPointer<Ui_MainWindow> Ui_MainWindow_sp;

private slots:

	/*! \brief		Slot loads an existing UberCode-Scene */
	void							OnLoadScene();

	/*! \brief		Slot saves an existing UberCode-Scene */
	void							OnSaveScene();

	/*! \brief		Slot creates a new UberCode-Scene */
	void							OnNewScene();

	/*! \brief		Slot connected to all activity modifying scenes content */
	void							OnDocumentModified();

	/*! \brief      Slot shows a About-Box */
	void							OnShowAbout();

	/*! \brief      Slot creates a dialog to insert bundle-search paths */
	void							OnShowSettingsPathBundles();

	/*! \brief		Slot Refreshing/Rescanning folders for new bundles/blocks */
	void							OnBundleRefresh();

private:
	UCWindowMain();
	~UCWindowMain();
	UCWindowMain( const UCWindowMain& obj );
	UCWindowMain& operator=( const UCWindowMain& obj );

	/*! \brief		Connects all the actions which are created by UberCode.ui and defined in class Ui_MainWindow */
	void							ConnectActions();

	virtual void					Initialize();

	virtual void					Uninitialize();


	Ui_MainWindow_sp				m_UIWindow; 	/*!< QT-UIInstance of the main window generated by MainWindow.ui, All Actions and Menus are defined in this object */
	UCDialogPathBundles_sp			m_UIDialogSettingBundlePath; 	/*!< Dialog shown on menu invoke: settings/ bundle paths - will be created in OnShowSettingsPathBundles  */

	friend class UCSingleton<UCWindowMain>;
};

}
